version: "3.9"

services:
  database:
    image: postgres:15
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=bank

  redis:
    image: redis:7-alpine

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_SOURCE=postgresql://root:mysecretpassword@database/bank?sslmode=disable
      - REDIS_ADDRESS=redis:6868
      - DB_DRIVER=postgres
      - SERVER_ADDRESS=0.0.0.0:8080
      - TOKEN_SYMMETRIC_KEY=dfjhslkdjfmsqmdifooierfnvcnqqijd
    depends_on:
      - database
      - redis
    entrypoint: ["/app/wait-for.sh", "database:5432", "--", "/app/start.sh"]
    command: ["/app/main"]
