version: "3.9"

services:
  database:
    image: postgres:15
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=bank

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_SOURCE=postgresql://root:mysecretpassword@database/bank?sslmode=disable
    depends_on:
      - database
    entrypoint: ["/app/wait-for.sh", "database:5432", "--", "/app/start.sh"]
    command: ["/app/main"]
